version: '3.9'

services:
  db:
    image: ankane/pgvector:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./whisper_models:/root/.cache/whisper

volumes:
  pgdata: